[package]
name = "game-connection"
version = "0.1.0"
edition = "2021"

[lib]
name = "conn"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/bin.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"